# Server
server:
  port: ${appPort}
  address: 0.0.0.0
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${keyStorePassword}
    key-store-type: PKCS12
spring:
  profiles:
    active: production
  sql:
    init:
      platform: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    table: schema_version
  web:
    client:
      connect-timeout: 5000     # Connection timeout in milliseconds
      read-timeout: 10000       # Read timeout in milliseconds

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      enabled: true
    prometheus:
      enabled: true

# Swagger
application:
  title: AccountAble-API
  description: Manage personal finances
  version: V1
springdoc:
  swagger-ui:
    oauth:
      appName: ${application.title}
    operationsSorter: alpha
  show-actuator: true

# JWT
jwt:
  expire-in-seconds: 864000
refresh-token:
  expire-in-seconds: 2592000
rsa:
  private-key: ${rsaPrivateKey}
  public-key: ${rsaPublicKey}
encryption:
  aes-secret-key: ${aesSecretKey}

currency:
  api:
    url: "https://v6.exchangerate-api.com/v6/{apiKey}/latest/{baseCurrency}"
    key: ${currencyApiKey}
    base: USD

metal:
  gold:
    url: "https://www.ideabeam.com/finance/rates/goldprice.php"
    xpath: "/html/body/div[2]/div[3]/div[3]/div/table/tbody/tr[4]/td[2]"

frontend:
  url: ${frontendUrl}

email:
  mailersend:
    api-token: ${mailersendToken}
  sender:
    name: ${emailSenderName}
    email: ${emailSenderEmail}

ocr:
  api-url: ${ocrApiUrl}
