global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'accountable-api'
    metrics_path: '/actuator/prometheus'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ 'accountable-api:8443' ]
