version: '3.1'

services:
  db:
    extends:
      file: common-services.yml
      service: db
    networks:
      - accountable-app-network
    restart: always
  app:
    container_name: accountable-api
    image: mithwick93/accountable-api
    build:
      context: ../
      dockerfile: ./infrastructure/Dockerfile
    networks:
      - accountable-app-network
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: "${DB_URL}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      CURRENCY_API_KEY: "${CURRENCY_API_KEY}"
      RSA_PRIVATE_KEY: "${RSA_PRIVATE_KEY}"
      RSA_PUBLIC_KEY: "${RSA_PUBLIC_KEY}"

volumes:
  accountable-mysql-data:

networks:
  accountable-app-network: