version: '3.1'

services:
  db:
    extends:
      file: common-services.yml
      service: db
    networks:
      - accountable-app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
        reservations:
          cpus: "0.5"
          memory: "512M"

  app:
    container_name: accountable-api
    build:
      context: ../
      dockerfile: ./infrastructure/Dockerfile
    networks:
      - accountable-app-network
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: "${DB_URL}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      CURRENCY_API_KEY: "${CURRENCY_API_KEY}"
      RSA_PRIVATE_KEY: "${RSA_PRIVATE_KEY}"
      RSA_PUBLIC_KEY: "${RSA_PUBLIC_KEY}"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "4G"
        reservations:
          cpus: "0.5"
          memory: "2G"

volumes:
  accountable-mysql-data:

networks:
  accountable-app-network: