CREATE TABLE transaction_templates
(
    id                     INT AUTO_INCREMENT PRIMARY KEY,
    name                   VARCHAR(255)                                                                        NOT NULL,
    description            TEXT                                                                                NULL,
    type                   ENUM ('INCOME', 'EXPENSE', 'TRANSFER')                                              NOT NULL,
    category_id            INT                                                                                 NULL,
    amount                 DECIMAL(19, 4)                                                                      NOT NULL,
    currency_id            INT                                                                                 NOT NULL,
    user_id                INT                                                                                 NOT NULL,
    from_asset_id          INT                                                                                 NULL,
    to_asset_id            INT                                                                                 NULL,
    from_payment_system_id INT                                                                                 NULL,
    to_payment_system_id   INT                                                                                 NULL,
    frequency              ENUM ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY')                                       NULL,
    day_of_week            ENUM ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY') NULL,
    day_of_month           TINYINT                                                                             NULL,
    month_of_year          TINYINT                                                                             NULL,
    start_date             DATE                                                                                NULL,
    end_date               DATE                                                                                NULL,
    created                TIMESTAMP                                                                           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified               TIMESTAMP                                                                           NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES transaction_categories (id),
    FOREIGN KEY (currency_id) REFERENCES currencies (id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (from_asset_id) REFERENCES assets (id),
    FOREIGN KEY (to_asset_id) REFERENCES assets (id),
    FOREIGN KEY (from_payment_system_id) REFERENCES payment_systems (id),
    FOREIGN KEY (to_payment_system_id) REFERENCES payment_systems (id)
);
